version: '3.5'
services:
#Services
 symfony:
  build:
    context: build
    args:
     ENVPATH: symfony.env
  environment:
  - SYMFONYV=^5.4
  - PROJNAME=symfony_project
  hostname: symfony
  ports:
  - "80:8000"
  volumes:
  - ./symfony_project:/symfony_project

