services:
#Services
 dvwa:
  image: javierfpisc/brs_dvwa:latest
  build:
    context: build
    args:
      BASE_IMAGE: "javierfpisc/trixie:network"
      DB: dvwa
      DBUSER: dvwa
      DBPASS: p@ssw0rd


