version: '3.5'
services:
#Services
 ossec-server:
  build:
    context: build
    args:
     ENVPATH: ossec-server.env
 ossec-agent:
  build:
    context: build
    args:
     ENVPATH: ossec-agent.env
