services:
#Services
#  bullseye_net:
#   build:
#     context: build
#     args:
#      ENVPATH: bullseye_net.env
 bookworm_hardening:
  image: javierfpisc/bookworm:hardening
  build:
    context: 12_hardening
    args:
     BASE_IMAGE: debian:bookworm
