version: '3.5'
services:
#Services
 nginx:
  build:
    context: build
    args:
     ENVPATH: nginx.env
 nginx_modsec:
  build:
    context: build
    dockerfile: Dockerfile_modsec
    args:
     ENVPATH: nginx_modsec.env


