version: '3.5'
services:
#Services
 graylog:
  build:
    context: build
    args:
     ENVPATH: graylog.env
  hostname: graylog
  cap_add:
  - ALL
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock



