services:
#Services
#  elk:
#   build:
#     context: build
#     args:
#      ENVPATH: elk.env
 elk:
  image: javierfpisc/elk:8.15.1
  build:
    context: build
    args:
     BASE_IMAGE: sebp/elk:8.15.1
  environment:
    - ELK_VERSION=8.15.1
