services:
#Services
#  apache_vuln:
#   image: javierfpisc/apache_vuln:2.4.49
#   build:
#     context: build
#     args:
#      BASE_IMAGE: debian:bookworm
#      APACHE_VERSION: 2.4.49
 apache_vuln:
  image: javierfpisc/apache_vuln:2.4.49
  build:
    context: build
    args:
     BASE_IMAGE: httpd:2.4.49
