services:
#Services
 ssh_auditbeat:
  image: javierfpisc/ssh_auditbeat:ssh_8.8p1
  build:
    context: build
    args:
     BASE_IMAGE: debian:bookworm
     SSH_VERSION: 8.8p1
     AUDITBEAT_VERSION: 8.17.2
     ELK_SERVER: 192.168.120.200

