version: '3.5'
services:
#Services
 service:
  build:
    context: build
    args:
     ENVPATH: service.env
  environment:
   #Nombre del directorio donde reside docker-compose.yml para despliegue de los services
   SERVICE: service
   DOCKER_HOST: tcp://172.17.0.1:2375
  hostname: dcompose-service
  cap_add:
  - ALL



